### ISSUE TITLE
Credits need updating

### ISSUE THREAD

**Issue by milestorme** [Artanisx/mod-solo-lfg#1]
you should add original script credits to this.
[Traesh: Original Script](https://github.com/Traesh) 

This is released under MIT license removing any credits will result in github action.

**Comment by Artanisx** [comment]
Sorry, for some reason Githut did not notify me. Credits updated as requested :)

**Comment by milestorme** [comment]
Sorry I think you miss understood , Traesh was the original script creator https://github.com/Traesh need to add him to credits as I have on my repo

**Comment by Artanisx** [comment]
Oops. Fixed now! :)
